containers:
  flye2: "docker://quay.io/biocontainers/flye:2.9.6--py313h7fbb527_1"
  goldrush: "docker://quay.io/biocontainers/goldrush:1.2.2--py312h248b54c_1"
  ntlink: "docker://quay.io/biocontainers/ntlink:1.3.11--py313h380480a_2"
  verkko2: "docker://quay.io/biocontainers/verkko:2.3.2--hb0edd9e_0"
