# =============================================================================
# LOCAL TEST CONFIGURATION
# =============================================================================
#
# Uses Nicolas's previously extracted real Chr21 30x reads.
#
# No chromosome extraction is performed in this mode.
# =============================================================================

input_mode: "chr21_fastq"

input_root: "/home/nicolas/lrs_benchmarking/final_report_files/snakemake_assemblers_benchmarking/benchmark_chr21_real/inputs/final_normalized"

threads: 4

resources:
  mapping_threads: 4
  flye_threads: 4
  goldrush_threads: 4
  ntlink_threads: 4
  verkko_threads: 4

  mapping_mem_mb: 8000
  flye_mem_mb: 12000
  goldrush_mem_mb: 12000
  goldrush_shm_size: "4g"
  ntlink_mem_mb: 8000
  verkko_mem_mb: 9000
  verkko_local_memory_gb: 8
